package Temp;

public class QuestionTypes {

	private static final String Question_Response_type = "Question_Response_type";
	private static final String Fill_In_The_Blank_type = "Fill_In_The_Blank_type";
	private static final String Multiple_Choice_type = "Multiple_Choice_type";
	private static final String Picture_Response_type = "Picture_Response_type";
	private static final String Multi_Answer_type = "Multi_Answer_type";
	private static final String Multiple_Choice_With_Multiple_Answers_type = "Multiple_Choice_With_Multiple_Answers_type";
	private static final String Matching_type = "Matching_type";
	private static final String Auto_Generated_type = "Auto_Generated_type";
	private static final String Graded_Question_type = "Graded_Question_type";
	private static final String Timed_Question_type = "Timed_Question_type";
	
	/**
	 * @return the questionResponseType
	 */
	public static String getQuestionResponseType() {
		return Question_Response_type;
	}
	
	/**
	 * @return the fillInTheBlankType
	 */
	public static String getFillInTheBlankType() {
		return Fill_In_The_Blank_type;
	}

	/**
	 * @return the multipleChoiceType
	 */
	public static String getMultipleChoiceType() {
		return Multiple_Choice_type;
	}

	/**
	 * @return the pictureResponseType
	 */
	public static String getPictureResponseType() {
		return Picture_Response_type;
	}

	/**
	 * @return the multiAnswerType
	 */
	public static String getMultiAnswerType() {
		return Multi_Answer_type;
	}

	/**
	 * @return the multipleChoiceWithMultipleAnswersType
	 */
	public static String getMultipleChoiceWithMultipleAnswersType() {
		return Multiple_Choice_With_Multiple_Answers_type;
	}


	/**
	 * @return the matchingTtype
	 */
	public static String getMatchingType() {
		return Matching_type;
	}
	
	/**
	 * @return the autoGeneratedType
	 */
	public static String getAutoGeneratedType() {
		return Auto_Generated_type;
	}

	/**
	 * @return the gradedQuestionType
	 */
	public static String getGradedQuestionType() {
		return Graded_Question_type;
	}

	/**
	 * @return the timedQuestionType
	 */
	public static String getTimedQuestionType() {
		return Timed_Question_type;
	}
	
}
